# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-01 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='category_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category', verbose_name='商品类型图片'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='logo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='标识'),
        ),
    ]
