# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-04 07:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20191201_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbanner',
            name='goods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.ProductSKU', verbose_name='商品'),
        ),
    ]
