# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-04 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20191204_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionpc',
            name='url',
            field=models.URLField(null=True, verbose_name='互动连接'),
        ),
    ]
