# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-04 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20191204_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionpc',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='互动连接'),
        ),
    ]
