# Generated by Django 3.0.4 on 2020-03-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20191204_2200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsku',
            options={'verbose_name': '商品SKU', 'verbose_name_plural': '商品SKU'},
        ),
        migrations.RenameField(
            model_name='productbanner',
            old_name='goods',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='goods',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='typeshow',
            old_name='goods',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='promotionpc',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='互动连接'),
        ),
    ]
