# Generated by Django 3.0.4 on 2020-03-31 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191128_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='goods',
            new_name='product',
        ),
    ]
